name: Make Test
run-name: ${{ github.actor }} is testing out Makefiles 🚀
on:
  push:
    branches:
      - main
jobs:
  Run-Make-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make test
