name: pip Test
run-name: ${{ github.actor }} is testing out pip 🚀
on:
  push:
    branches:
      - main
jobs:
  Run-pip-Test:
    runs-on: ubuntu-latest
    steps:
      - run: python -V
      - run: pip -V
      - run: pip freeze
      - run: pip install rich
